### ISSUE TITLE
Generic host builder and UnitTest: ISchedulerFactory.GetScheduler operation returns null

### ISSUE THREAD

**Issue by reponemec** [quartznet/quartznet#1099]
Please examine these two unit test's scenarios:
```
   [TestFixture]
    class GetSchedulerTest
    {
        [Test]
        public async Task GetSchedulerTestAsync()
        {
            const string schedulerName = "Test scheduler";

            var host = Microsoft.Extensions.Hosting.Host
                .CreateDefaultBuilder()
                .ConfigureServices((context, services) =>
                {
                    services.AddQuartz(cfg =>
                    {
                        cfg.SchedulerName = schedulerName;
                    });
                })
                .Build();

            var serviceProvider = host.Services;
            var schedulerFactory = serviceProvider.GetRequiredService<ISchedulerFactory>();

            //SCENARIO 1
            //var _scheduler = await schedulerFactory.GetScheduler(schedulerName); //_scheduler refers to null.
            //Assert.NotNull(_scheduler);  //Exception.

            //SCENARIO 2
            var kick = await schedulerFactory.GetScheduler(); //Kick it off.
            var _scheduler = await schedulerFactory.GetScheduler(schedulerName); //Now _scheduler refers to a valid instance.
            Assert.NotNull(_scheduler); //Success.
        }
    }
```
In SCENARIO 1, _scheduler refers to null, whereas in SCENARIO 2 it refers to a valid instance. Is there something wrong at code setup ? 
Quartz scheduler version: 3.2.3.0.

**Comment by lahma** [comment]
This behavior is because the call `await schedulerFactory.GetScheduler();` is required to happen in order for the named version lookup to work. Quartz DI integration doesn't currently instantiate the actual scheduler instance from factory as it's async operation. Only after the default `GetScheduler()` call the scheduler is actually built and registered.

The current state is that DI is supposed to have single scheduler factory and thus there's no need to use the named lookup ever, even though it's available in the interface. 

The case would be different if you were running multiple factories in the same process and then would have the need to distinguish between built scheduler instances.

Does this make sense?

**Comment by reponemec** [comment]
Yes, it seems that multiple factories are needed in one DI environment.

The idea is that IScheduler will be a private helper part of my .net standard library that encapsulate many DI services with dependency on IScheduler. 
Library will be used by different consumers suporting .net core's generic host builder (console app, ASP.NET Core app).
These DI services, including quartz services as their private part, are then hooked up into the consumer application using special all-in-one IHostBuilder's extension method. The problem is that these consumers can, potentialy, use their own schedulers from their own configured factories independently of others.
And all is running in a single process of course.

**Comment by lahma** [comment]
If you find out a sustainable way to improve, I'd love to see a PR for this.

**Comment by lahma** [comment]
Closing as there doesn't seem to actionable items.
