### ISSUE TITLE
WithDailyTimeIntervalSchedule

### ISSUE THREAD

**Issue by krzysztofsitnik** [quartznet/quartznet#1152]
**Describe the bug**

TriggerBuilder.WithDailyTimeIntervalSchedule has default interval of 1 minute. 
Wouldn't it be more understandable to have there 24 hours default interval, as the name suggests? 

**Version used**

3.0.4

**To Reproduce**
`var sampleTrigger = TriggerBuilder
                .Create()
                .StartNow()
                .WithDailyTimentervalSchedule(builder =>
                    .StartingDailyAt(TimeOfDay.HourAndMinuteOfDay(23, 56)))
                .Build();`

**Expected behavior**

I expect that trigger to work once a day, not each minute after the time put in StartingDailyAt.

**Additional context**

I'm not the only person which find it as misunderstanding.
[https://stackoverflow.com/questions/12735750/quartz-net-how-to-create-a-daily-schedule-that-does-not-gain-1-minute-per-day](url)

**Comment by chaquotay** [comment]
> I'm not the only person which find it as misunderstanding.

I am also one of them 😢

**Comment by lahma** [comment]
Would it make it more clear to allow passing default interval as part of the method signature, like so (didn't check against IDE so there be dragons):

```csharp
var sampleTrigger = TriggerBuilder .Create()
    .StartNow()
    .WithDailyTimentervalSchedule(IntervalUnit.Day, x => x
        .StartingDailyAt(TimeOfDay.HourAndMinuteOfDay(23, 56)
    )
)
.Build();
```

Just trying to find a solution that wouldn't be breaking for existing users but yet would make API and it's parameters discoverable.

**Comment by chaquotay** [comment]
I'm not sure. I just assumed (my bad) that, given the name `WithDailyTimeIntervalSchedule`, the default interval would be "one day". But I see that changing this is not an option, because it will most likely break the existing code.

Maybe adding clarifiying documentation regarding the default interval to `WithDailyTimeIntervalSchedule` in https://github.com/quartznet/quartznet/blob/35b8532dc005af2fc907b6d2516c2e4bf40f833b/src/Quartz/DailyTimeIntervalScheduleBuilder.cs#L497 is a good and easy step into the right direction?
