### ISSUE TITLE
Priority documentation

### ISSUE THREAD

**Issue by monrealis** [quartznet/quartznet#1459]
Could you please document somewhere very clearly (other than in code) that the bigger number in Priority indicates higher priority? It's far from intuitive (for example, in Jira lower values indicate higher priority -  https://beam.apache.org/contribute/jira-priorities/ ).

**Comment by lahma** [comment]
The priority follows .NET's ThreadPriority enum values. The documentation accepts PRs, would you like to submit one?

**Comment by monrealis** [comment]
I'm struggling to understand myself :) But it seems that the only thing that priority is similar to `ThreadPriority` is the fact that priority is higher for higher int values.
* 5 is default in Quartz, 2 is normal in `ThreadPriority`
* max int is highest priority Quartz, 4 is highest priority in `ThreadPriority`
* if it had something to do with `ThreadPriority`, Quartz should accept ThreadPriority as a parameter

**Comment by drieseng** [comment]
@monrealis I don't think @lahma meant to say that priority uses the same values. It uses a similar numbering scheme where lower numbers are considered lower priority.

I'd advice against using **ThreadPriority** since we're not using it to prioritize threads. I'm ok with introducing an enum, but it would limit the number of different priorities one can have. I'm not sure we want this.
