### ISSUE TITLE
Quartz.Net stopped when IIS app-pool recycle

### ISSUE THREAD

**Issue by MuraliM** [quartznet/quartznet#180]
I am using Quartz.Net in my asp.net application and we are ending up with IIS recycling and it stops working.

We hosted our application in external hosting provider, so we cannot play with config file explained http://weblogs.asp.net/scottgu/auto-start-asp-net-applications-vs-2010-and-net-4-0-series

Is there a way to automatically make the Quartz.Net alive when IIS restarted/recycled?
Tried following this http://weblog.west-wind.com/posts/2007/May/10/Forcing-an-ASPNET-Application-to-stay-alive . But not working

**Comment by Worthy7** [comment]
Hello, 2017 here. Solution is some simple settings changes in IIS, I believe 8 or higher.
The issue is that the application is being recycled, and is not being prompted to start up again. There is now a settings to enable application preload:

https://blogs.msdn.microsoft.com/vijaysk/2012/10/11/iis-8-whats-new-website-settings/
Install the feature, and it will automatically enable preload on all of your sites.

**Comment by lahma** [comment]
Thanks, I've updated [FAQ](https://www.quartz-scheduler.net/documentation/faq.html) with this, right there at the bottom.
