### ISSUE TITLE
Common.Logging 3.0.0 is incompatible 

### ISSUE THREAD

**Issue by GieltjE** [quartznet/quartznet#226]
The latest update for Common.Logging is unfortunately incompatible with Quartz.net.

Would it be be to much to ask to detect the availability of Common.Logging and just work without logging if it is not present?

**Comment by meixger** [comment]
Hopefully Quartz.net could adopt Common.Logging 3.0.0 because of the possibility to use log4net's ThreadContext.Properties[] or NLog's MappedDiagnosticsContext :+1:

**Comment by lahma** [comment]
I'll update to CL 3.0 with 2.3.1 release.

**Comment by remcoros** [comment]
The update from CL 2.3 to 3.0 is a MAJOR and BREAKING change. Why was this done in a minor Quartz update? 

What seemed to be a 'patch' release (2.3 > 2.3.1), caused a dependency chain hell in all dependant libraries (Ninject extensions / Topshelf integration / etc), because they do not provide a version using Common Logging 3.

This is not semantic versioning, and in my opinion, this should have been done in a 2.4 quartz release, to communicate properly that it (can) contain breaking changes.

Please think about this when pushing such major changes.
