### ISSUE TITLE
cannot run quart with asp.net vnext

### ISSUE THREAD

**Issue by mrgonext** [quartznet/quartznet#227]
cannot run quart with asp.net vnext  vs 2015 preview

**Comment by lahma** [comment]
Would you care to elaborate?

**Comment by mrgonext** [comment]
Sorry, if I dont care to elaborate why should I post the issue to the project?
maybe I dont describe detail the issue, you should ask more...
![issue](https://cloud.githubusercontent.com/assets/6385889/5737769/8e35d05e-9c17-11e4-850b-5b248e1bd8a1.png)

**Comment by Jawvig** [comment]
OP, Mark is doing a sterling job at maintaining this library. I think he responded in a polite manner to you. Please try to be civil in your response. Everyone else: Sorry for weighing in with a non-technical point. It just pains me to see this kind of response. I won't be drawn on this any further, though.

**Comment by lahma** [comment]
The problem seems to reside with using ASP.NET Core 5.0. If ones removes "aspnetcore50" from project.json everything works fine. Unfortunately VS 2015 does not give a hint what is the actual cause for DLL being incompatible (I have very little experience with ASP.NET 5.0 Core).

@mrgonext you have created an ASP.NET web site and named as ConsoleApplication. Are you trying to develop a console or web based solution?

**Comment by mrgonext** [comment]
Thank you very much!, I've removed asp.net core 5.0 and it worked!
@lahma I just create a new ASP.Net 5 console application project.
I'm testing quartz with asp.net vnext to consider upgrade my current project.
