### ISSUE TITLE
BinaryFormatter removal

### ISSUE THREAD

**Issue by adamsitnik** [quartznet/quartznet#2324]
Hello!

I am trying to wrap my head about the dependency on `BinaryFormatter` and I need some help.

1. The only direct dependency to `BinaryFormatter` in non-test source code is the usage in [BinaryObjectSerializer](https://github.com/quartznet/quartznet/blob/main/src/Quartz/Simpl/BinaryObjectSerializer.cs).
2. `BinaryObjectSerializer` implements `IObjectSerializer`, it's spread in multiple places in the source code, but it seems that `StdAdoDelegate` is the only type that actually uses it (other places just store it to pass it somewhere else):
https://github.com/quartznet/quartznet/blob/72fce9c599e020f4db0b0c77d277f9971d947a6f/src/Quartz/Impl/AdoJobStore/StdAdoDelegate.cs#L60
https://github.com/quartznet/quartznet/blob/72fce9c599e020f4db0b0c77d277f9971d947a6f/src/Quartz/Impl/AdoJobStore/StdAdoDelegate.cs#L477
https://github.com/quartznet/quartznet/blob/72fce9c599e020f4db0b0c77d277f9971d947a6f/src/Quartz/Impl/AdoJobStore/StdAdoDelegate.cs#L568
3. It seems that the serialization exposed by `StdAdoDelegate` is used to:
a) Serialize all implementations of public interface `ICalendar`:
https://github.com/quartznet/quartznet/blob/72fce9c599e020f4db0b0c77d277f9971d947a6f/src/Quartz/Impl/AdoJobStore/StdAdoDelegate.Calendars.cs#L14
https://github.com/quartznet/quartznet/blob/72fce9c599e020f4db0b0c77d277f9971d947a6f/src/Quartz/Impl/AdoJobStore/StdAdoDelegate.Calendars.cs#L31
b) Serialize `NameValueCollection` (more or less a `Dictionary<string, string>` provided by BCL):
https://github.com/quartznet/quartznet/blob/72fce9c599e020f4db0b0c77d277f9971d947a6f/src/Quartz/Impl/AdoJobStore/StdAdoDelegate.cs#L507-L508
c) Serialize sealed `JobDataMap` (more or less a custom wrapper for `Dictionary<string, object>`)
https://github.com/quartznet/quartznet/blob/72fce9c599e020f4db0b0c77d277f9971d947a6f/src/Quartz/Impl/AdoJobStore/StdAdoDelegate.Jobs.cs#L272
d) Serialize all implementations of public interface `IOperableTrigger`:
https://github.com/quartznet/quartznet/blob/72fce9c599e020f4db0b0c77d277f9971d947a6f/src/Quartz/Impl/AdoJobStore/StdAdoDelegate.Triggers.cs#L328
https://github.com/quartznet/quartznet/blob/72fce9c599e020f4db0b0c77d277f9971d947a6f/src/Quartz/Impl/AdoJobStore/StdAdoDelegate.Triggers.cs#L442
e) Try to find what is not serializable in `JobDataMap` by trying to serialize all values and stopping on first that fails to serialize.
https://github.com/quartznet/quartznet/blob/72fce9c599e020f4db0b0c77d277f9971d947a6f/src/Quartz/Impl/AdoJobStore/StdAdoDelegate.Jobs.cs#L270-L276
https://github.com/quartznet/quartznet/blob/72fce9c599e020f4db0b0c77d277f9971d947a6f/src/Quartz/Impl/AdoJobStore/StdAdoDelegate.cs#L482-L489

My questions:
1. Are the observations listed above correct? Have I missed any serialization scenario?
2. How common is for the users to provide custom `ICalendar` implementations and persist it? Do all of the users have to implement [ICalendarSerializer](https://www.quartz-scheduler.net/documentation/quartz-3.x/packages/json-serialization.html#customizing-calendar-serialization)?
3. What kind of values can be used by the end users in `JobDataMap`? Just primitive types like `int` and `string` or perhaps this can be literally anything that is `[Serializable]`, including user-defined types?
4. The description of `IOperableTrigger` says that it's internal despite being public. Does it mean that users should not derive from this interface and we can focus only on the `IOperableTrigger` implementations provided by the library?
https://github.com/quartznet/quartznet/blob/72fce9c599e020f4db0b0c77d277f9971d947a6f/src/Quartz/SPI/IOperableTrigger.cs#L4
5. How common is for the users to derive a custom type from abstract class `AbstractTrigger` (that implements `IOperableTrigger`) and persist it?
https://github.com/quartznet/quartznet/blob/72fce9c599e020f4db0b0c77d277f9971d947a6f/src/Quartz/Impl/Triggers/AbstractTrigger.cs#L55-L56

Thanks!

**Comment by lahma** [comment]
Thank you for taking the interest in Quartz and its binary formatter issues! I'll give some background first which might help with other answers...

From version 1.0 onwards the binary formatter has been the solution to store state in database and also to communicate with remote Quartz scheduler. User's have been able to export `IScheduler` as a remoting service and then call it's methods (`Start`, `Stop`, `Pause` etc). Remoting support has (naturally) never been ported to to NET Core/nestandard2.0. 

While serialization of custom calendars and triggers is possible (when database schema cannot handle their data), I'd think it's quite rare. I can't remember issues about such serialization - I might well be wrong too as billion dollar companies rarely come back telling about their successes.

Binary serialization for database was the natural choice when porting from Java version where it was also the way to go (as bad as it is in hindsight). Users can store *anything* that just serializes, but there's configuration switch which is recommended `usePrroperties = true` which turns the mode to allow only values to be strings. All following the Java logic. Also it's using byte[] kind of column data type in database which of course is not ideal storage format for JSON in modern databases.

From version 3.0 (released in 2017) onwards Quartz has required you to do an informed decision about the serializer being used, scheduler throwing error when persistence is configured without serialization implementation:

https://github.com/quartznet/quartznet/blob/bf813bc02c9bddc7bd7a50ddc027687563aa657d/src/Quartz/Impl/StdSchedulerFactory.cs#L709-L716

The `json` maps to Newtonsoft.Json, but ideally we would differentiate between `systemtextjson` and `newtonsoftjson` instead of general name (v4 could break this).

3.x is somewhat in maintenance mode and v4 development (`main`) should/could drop whole support for binary serialization. There's HTTP API replacing remoting in v4 for NET 6.0+ and it might also be an option that Quartz will *only* support NET 6.0+ from v4 onwards - v3 could be considered battle-tested solution for full framework usage and still allowing both remoting and binary serialization on that platform.

> Are the observations listed above correct? Have I missed any serialization scenario?

I believe you have found the most use cases, mainly it's the job data map that allows persisting state for a job/trigger between invocations and this state resides in database for cluster workers/failure resistance (`RAMJobStore `will forget everything in process restart).

> How common is for the users to provide custom ICalendar implementations and persist it? Do all of the users have to implement [ICalendarSerializer](https://www.quartz-scheduler.net/documentation/quartz-3.x/packages/json-serialization.html#customizing-calendar-serialization)?

I'm not aware of custom implementations (or NuGet packages offering those). Calendar serializer and others will probably be useful when Newtonsoft.Json will go (at least tried) sunsetting phase. System.Text.Json implementation is still missing but I think v8 of STJ if mature enough to work here. I just haven't had the time.

> What kind of values can be used by the end users in JobDataMap? Just primitive types like int and string or perhaps this can be literally anything that is [Serializable], including user-defined types?

It could be anything. Quartz documentation suggests that it's better to store only primitive types, but it's not enforced by default.

For migration scenarios I would probably create custom `IObjectSerializer` which would be able to read binary data and always write JSON, so a composite serializer allowing old format and serializing new format. Could be painful for large installations.

> The description of IOperableTrigger says that it's internal despite being public. Does it mean that users should not derive from this interface and we can focus only on the IOperableTrigger implementations provided by the library?

`IOperableTrigger` offers services that Quartz needs to do its job. Services that should not be called or relied upon to be there by regular user code. Custom triggers should be quite rare case, maybe people would be overriding some existing ones, I don't have any data on this.

>  How common is for the users to derive a custom type from abstract class AbstractTrigger (that implements IOperableTrigger) and persist it?

No data for this either, but I'd say a rare case and could be considered as breakable for v4 and then later think how to support if needed by the billion dollar companies behind the curtains 😉 

So as a short summary, think v4 in progress should probably not support binary serialization at all, but allow people to write migrating serializer reading data and writing JSON. It's all open for discussion though.
