### ISSUE TITLE
Recently i have been getting this error "JobBuilder.cs" not found

### ISSUE THREAD

**Issue by joeldsouza1992** [quartznet/quartznet#276]
Need your help on this asap

**Comment by Jawvig** [comment]
Is this whilst debugging? Do you have the full stack trace of the error, perhaps by running it outside of debug mode and looking at some logs? Also, maybe you can describe a little bit about your solution and what is happening at the point this error occurs? The Quartz.Net version number you're using would also be helpful.

**Comment by joeldsouza1992** [comment]
apparently this arises only during debug, the functionality is working fine. You can close the issue :D

**Comment by Jawvig** [comment]
I'm glad it's not a problem. I suspect it was a thrown but handled error and your Visual Studio debug settings were breaking on thrown errors rather than just unhandled errors.

By the way, I think you can close the issue yourself, can you not? I don't have the authorisation! :-) Otherwise we'll wait for Marko to do it.
