### ISSUE TITLE
Build.cmd errors in v3

### ISSUE THREAD

**Issue by GieltjE** [quartznet/quartznet#299]
```
  <target name="restore-nuget-packages" unless="${target::has-executed('restore-nuget-packages')}">
	<exec program="${nuget.location}" commandline="restore Quartz.2010.sln" />
	<exec program="${nuget.location}" commandline="restore Quartz.Server.2010.sln" />
  </target>
```
Doesn't work as Quartz.2010.sln nor Quartz.Server.2010.sln exists, using just Quartz.sln works.

```
<include name="${common-logging-dll}" />
```
Just throws an exception. (removing it seems to be the usefull answer).

It also appears to use an old compiler on my system as newer for some reason an older compiler is selected (e.g. C# 6.0 expression bodies don't compile).

Also I don't see any reason not to start referencing 4.5.2, everybody should have upgraded a long time ago.

**Comment by cknightdevelopment** [comment]
I am having the same issues. It seems like NAnt can't use the latest compiler that can make sense of the C# 6 language features. How are people getting around this? Can the branch be updated to a working and correct state?

**Comment by lahma** [comment]
I've updated to intermediate solution where Quartz.sln should build pretty cleanly with standard Visual Studio 2015. There's also Quartz.All.sln that contains also the server and web projects.

Hope this helps.

**Comment by cknightdevelopment** [comment]
Terrific! Thanks, things are working well for me now.

- Chris Knight

**Comment by GieltjE** [comment]
I'm still having issues with the nuget packages:
 - Oracle remains unsolved
 - odp.net.managed is specified as a version that is no longer obtainable
 - "Error occurred while restoring NuGet packages: An item with the same key has already been added."

**Comment by cknightdevelopment** [comment]
I had that issue too. Here is what I had to do:

   - Open the `Quartz.sln` solution in Visual Studio 2015 to restore the
   nuget packages using (rather than using the build script)
   - Note: I also removed the `<package id="LibLog" version="4.2.1"
      targetFramework="net45" />` reference in the Quartz project's
      packages.config and replaced it with `<package id="log4net"
version="2.0.3"
      targetFramework="net45" />` so that it matches the other projects (I am
      assuming this was overlooked)
   - Then I just ran '.\tools\NAnt\bin\NAnt.exe generate-assembly-info' to
   create the `AssemblyInfo.cs` file

After doing this I could just build from within Visual Studio and not worry
about NAnt.

**Comment by cknightdevelopment** [comment]
I had that issue too. Here is what I had to do:

   - Open the `Quartz.sln` solution in Visual Studio 2015 to restore the
   nuget packages using (rather than using the build script)
   - Note: I also removed the `<package id="LibLog" version="4.2.1"
      targetFramework="net45" />` reference in the Quartz project's
      packages.config and replaced it with `<package id="log4net"
version="2.0.3"
      targetFramework="net45" />` so that it matches the other projects (I am
      assuming this was overlooked)
   - Then I just ran '.\tools\NAnt\bin\NAnt.exe generate-assembly-info' to
   create the `AssemblyInfo.cs` file

After doing this I could just build from within Visual Studio and not worry
about NAnt.
