### ISSUE TITLE
. NET4.0

### ISSUE THREAD

**Issue by 273168121** [quartznet/quartznet#616]
hi everyone, 3.X version  don't support. NET4.0？

**Comment by lahma** [comment]
Only .NET 4.5.2 and higher. Microsoft has also dropped support for earlier versions.

**Comment by 273168121** [comment]
But many people still use xp OS,  xp OS  not supported. NET4.0 +,
Thank you for reply!

**Comment by ocdtrekkie** [comment]
@273168121 You should not be on Windows XP, it is a massive risk.

**Comment by cedral** [comment]
@ocdtrekkie That is great and all. But we can't all live in a world of ideals.  He is probably a software developer who has to worry about what his customers might be using rather than what he would do left to his own devices. While it may be unfortunate, Server 2003 and XP both still have significant market share. For now I am stuck at 2.6.1 for just that reason.

**Comment by lahma** [comment]
Well one can always stay on 2.x series. Critical bug fixes will be available but no new feature development.
