### ISSUE TITLE
TimezoneId Aliases for China Standard Time is not working

### ISSUE THREAD

**Issue by panbohaha** [quartznet/quartznet#752]
TimezoneId Aliases for China Standard Time is not working

Right
```csharp
 timeZoneIdAliases["China Standard Time"] = "Asia/Shanghai";
```

**Comment by lahma** [comment]
This is part I'm afraid to change due to regional differences. They can be quite ambiguous. Can you try [Quartz.Plugins.TimeZoneConverter](https://www.nuget.org/packages/Quartz.Plugins.TimeZoneConverter/)? Guessing of times is deprecated functionality now that there is a better option with the plugin.
