### ISSUE TITLE
CronExpression.GetFinalFireTime throws exception in 3.1.0

### ISSUE THREAD

**Issue by kemsky** [quartznet/quartznet#905]
### Version: x.y.z
 
3.1.0

### Expected behavior

CronExpression.GetFinalFireTime() previously did not throw any exceptions (it turns out it did not work either)

### Actual behavior

Now NotImplementedException is thrown - it is a breaking change.

### Steps to reproduce

```csharp
var cron = new CronExpression(expression);
return cron.GetFinalFireTime()?.DateTime; // throws...
```

Not sure what is the best here solution here, maybe QUARTZ-423 should be implemented?

**Comment by lahma** [comment]
Yes this was changed in https://github.com/quartznet/quartznet/pull/731 , I think it's better to inform that this isn't doing the right thing instead of people relying it doing something. Seems that there's been at least a try on Java side to implement it: https://github.com/quartz-scheduler/quartz/pull/421 .

**Comment by lahma** [comment]
I think it's easiest to just revert the change as people don't seem to mind the wrong result as much as the exception.

**Comment by lahma** [comment]
Now there's also a suggestion on Java side for this to throw until it's implemented https://github.com/quartz-scheduler/quartz/issues/614 . I guess undefined behavior is hard.
