### ISSUE TITLE
Quartz as a  Service

### ISSUE THREAD

**Issue by ColinA64** [quartznet/quartznet#987]
Hi

I can  schedule jobs to both ramstore and database, but am having problems using Quartz as a service,  the install of the service seems fine,  attachments are testing the service when installed  with service running (issues)  not running seem ok I am new to Quartz so any help would be appreciated
![quartz_ServiceNotRunning](https://user-images.githubusercontent.com/69348790/95554960-fcaacc00-0a08-11eb-8cab-74e1a24167d3.PNG)
![Quartz_ServiceRunning](https://user-images.githubusercontent.com/69348790/95554967-fd436280-0a08-11eb-9ba0-647f206eb77c.PNG)

, TIA

**Comment by lahma** [comment]
So I presume that you need the remoting functionality to invoke scheduler remotely. This might be caused by some permission requirements that your principal running the Windows service is missing. Have you tried running the service with different permissions (different user), like network service?

If you don't need the remoting bits, you can just remove them from your configuration.
